### ISSUE TITLE
在下载页面内，拉动右侧的快速阅览按钮闪退。

### ISSUE THREAD

**Issue by qq1724737202** [UjuiUjuMandan/EhViewer#85]
### 复现步骤 / Step to reproduce

在下载页面内，拉动右侧的快速阅览按钮闪退。概率100%。在更新到最新的版本后也是闪退

### 预期行为 / Expected behaviour

在下载页面内应该下啦快速阅览至底部，但是拉动按钮后闪退退出应用。

### 实际行为 / Actual Behaviour

![Screenshot_2024-08-23-06-21-13-595_com miui thirdappassistant](https://github.com/user-attachments/assets/48ddb581-993a-4616-9a87-90e79c2bf8cf)

### 应用日志 / App logs

```
java.lang.IllegalStateException: Error: Placement happened before lookahead.
	at It0.b(Unknown Source:2)
	at sA0.J0(Unknown Source:115)
	at sA0.c0(Unknown Source:5)
	at r81.e(Unknown Source:14)
	at r81.f(Unknown Source:1)
	at xu.invoke(Unknown Source:70)
	at ZK0.d(Unknown Source:6)
	at pA0.a(Unknown Source:66)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.r(Unknown Source:103)
	at sA0.D0(Unknown Source:118)
	at Ot0.c0(Unknown Source:22)
	at qA0.a(Unknown Source:75)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.G0(Unknown Source:97)
	at sA0.J0(Unknown Source:118)
	at sA0.c0(Unknown Source:5)
	at r81.g(Unknown Source:14)
	at androidx.compose.foundation.layout.k.b(Unknown Source:39)
	at androidx.compose.foundation.layout.m.invoke(Unknown Source:21)
	at ZK0.d(Unknown Source:6)
	at pA0.a(Unknown Source:66)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.r(Unknown Source:103)
	at sA0.D0(Unknown Source:118)
	at Ot0.c0(Unknown Source:22)
	at r81.l(Unknown Source:25)
	at androidx.compose.ui.graphics.c.invoke(Unknown Source:12)
	at ZK0.d(Unknown Source:6)
	at Oz0.y1(Unknown Source:12)
	at Oz0.c0(Unknown Source:8)
	at r81.e(Unknown Source:14)
	at r81.f(Unknown Source:1)
	at lP0.invoke(Unknown Source:28)
	at ZK0.d(Unknown Source:6)
	at Oz0.y1(Unknown Source:12)
	at Oz0.c0(Unknown Source:8)
	at qA0.a(Unknown Source:75)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.G0(Unknown Source:97)
	at sA0.J0(Unknown Source:118)
	at sA0.c0(Unknown Source:5)
	at r81.e(Unknown Source:14)
	at r81.f(Unknown Source:1)
	at Nm1.invoke(Unknown Source:66)
	at ZK0.d(Unknown Source:6)
	at pA0.a(Unknown Source:66)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.r(Unknown Source:103)
	at sA0.D0(Unknown Source:118)
	at Ot0.c0(Unknown Source:22)
	at qA0.a(Unknown Source:75)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.G0(Unknown Source:97)
	at sA0.J0(Unknown Source:118)
	at sA0.c0(Unknown Source:5)
	at r81.e(Unknown Source:14)
	at r81.f(Unknown Source:1)
	at xu.invoke(Unknown Source:70)
	at ZK0.d(Unknown Source:6)
	at pA0.a(Unknown Source:66)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.r(Unknown Source:103)
	at sA0.D0(Unknown Source:118)
	at Ot0.c0(Unknown Source:22)
	at qA0.a(Unknown Source:75)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.G0(Unknown Source:97)
	at sA0.J0(Unknown Source:118)
	at sA0.c0(Unknown Source:5)
	at r81.e(Unknown Source:14)
	at r81.f(Unknown Source:1)
	at xu.invoke(Unknown Source:70)
	at ZK0.d(Unknown Source:6)
	at pA0.a(Unknown Source:66)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.r(Unknown Source:103)
	at sA0.D0(Unknown Source:118)
	at Ot0.c0(Unknown Source:22)
	at qA0.a(Unknown Source:75)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.G0(Unknown Source:97)
	at sA0.J0(Unknown Source:118)
	at sA0.c0(Unknown Source:5)
	at r81.g(Unknown Source:14)
	at androidx.compose.foundation.layout.k.b(Unknown Source:39)
	at androidx.compose.foundation.layout.m.invoke(Unknown Source:21)
	at ZK0.d(Unknown Source:6)
	at pA0.a(Unknown Source:66)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.r(Unknown Source:103)
	at sA0.D0(Unknown Source:118)
	at Ot0.c0(Unknown Source:22)
	at r81.l(Unknown Source:25)
	at androidx.compose.ui.graphics.c.invoke(Unknown Source:12)
	at ZK0.d(Unknown Source:6)
	at Oz0.y1(Unknown Source:12)
	at Oz0.c0(Unknown Source:8)
	at r81.e(Unknown Source:14)
	at r81.f(Unknown Source:1)
	at lP0.invoke(Unknown Source:28)
	at ZK0.d(Unknown Source:6)
	at Oz0.y1(Unknown Source:12)
	at Oz0.c0(Unknown Source:8)
	at r81.h(Unknown Source:67)
	at androidx.compose.foundation.layout.I.invoke(Unknown Source:5)
	at ZK0.d(Unknown Source:6)
	at Oz0.y1(Unknown Source:12)
	at Oz0.c0(Unknown Source:8)
	at qA0.a(Unknown Source:75)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.G0(Unknown Source:97)
	at sA0.J0(Unknown Source:118)
	at sA0.c0(Unknown Source:5)
	at r81.g(Unknown Source:14)
	at androidx.compose.foundation.layout.k.b(Unknown Source:39)
	at androidx.compose.foundation.layout.m.invoke(Unknown Source:21)
	at ZK0.d(Unknown Source:6)
	at pA0.a(Unknown Source:66)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.r(Unknown Source:103)
	at sA0.D0(Unknown Source:118)
	at Ot0.f0(Unknown Source:22)
	at qA0.a(Unknown Source:51)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.G0(Unknown Source:97)
	at sA0.J0(Unknown Source:118)
	at sA0.f0(Unknown Source:5)
	at cE0.l(Unknown Source:206)
	at aE0.invoke(Unknown Source:23)
	at zA0.d(Unknown Source:36)
	at bE0.d(Unknown Source:2)
	at BA0.d(Unknown Source:8)
	at pA0.a(Unknown Source:66)
	at RB1.d(Unknown Source:55)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.r(Unknown Source:103)
	at sA0.D0(Unknown Source:118)
	at Ot0.c0(Unknown Source:22)
	at r81.l(Unknown Source:25)
	at androidx.compose.ui.graphics.c.invoke(Unknown Source:12)
	at ZK0.d(Unknown Source:6)
	at Oz0.y1(Unknown Source:12)
	at Oz0.c0(Unknown Source:8)
	at r81.e(Unknown Source:14)
	at r81.f(Unknown Source:1)
	at uC0.invoke(Unknown Source:5)
	at ZK0.d(Unknown Source:6)
	at Oz0.y1(Unknown Source:12)
	at Oz0.c0(Unknown Source:8)
	at r81.h(Unknown Source:67)
	at androidx.compose.foundation.layout.q.invoke(Unknown Source:5)
	at ZK0.d(Unknown Source:6)
	at Oz0.y1(Unknown Source:12)
	at Oz0.c0(Unknown Source:8)
	at qA0.a(Unknown Source:75)
	at RB1.d(Unknown Source:113)
	at RC1.a(Unknown Source:51)
	at VC1.d(Unknown Source:128)
	at g21.b(Unknown Source:2)
	at sA0.G0(Unknown Source:97)
	at dA0.P(Unknown Source:43)
	at xN0.k(Unknown Source:133)
	at androidx.compose.ui.platform.x.u(Unknown Source:7)
	at dA0.k(Unknown Source:38)
	at wE0.j(Unknown Source:31)
	at sE0.r(Unknown Source:12)
	at sE0.f(Unknown Source:12)
	at EN.r(Unknown Source:45)
	at EN.f(Unknown Source:12)
	at QS0.r(Unknown Source:134)
	at QS0.f(Unknown Source:12)
	at hU.I(Unknown Source:4)
	at YA.w(Unknown Source:9)
	at RS0.c(Unknown Source:11)
	at FN.r(Unknown Source:42)
	at FN.f(Unknown Source:12)
	at hU.I(Unknown Source:4)
	at YA.w(Unknown Source:9)
	at HN.d(Unknown Source:6)
	at wE0.d(Unknown Source:92)
	at wE0.i(Unknown Source:8)
	at iE0.h(Unknown Source:4)
	at Hz1.a(Unknown Source:154)
	at Gz1.r(Unknown Source:132)
	at Gz1.f(Unknown Source:12)
	at Q.o0(Unknown Source:36)
	at FY1.H(Unknown Source:23)
	at FY1.I(Unknown Source:12)
	at Tq1.invoke(Unknown Source:1743)
	at androidx.compose.foundation.gestures.l0.j(Unknown Source:85)
	at androidx.compose.foundation.gestures.i0.r(Unknown Source:12)
	at kh.i(Unknown Source:8)
	at FY1.P(Unknown Source:80)
	at Ao.r(Unknown Source:104)
	at Ao.E(Unknown Source:32)
	at Ao.i(Unknown Source:16)
	at dJ1.i1(Unknown Source:50)
	at dJ1.U(Unknown Source:31)
	at zW0.f(Unknown Source:156)
	at zW0.f(Unknown Source:135)
	at zW0.f(Unknown Source:135)
	at zW0.f(Unknown Source:135)
	at zW0.f(Unknown Source:135)
	at zW0.f(Unknown Source:135)
	at Yn0.b(Unknown Source:29)
	at M91.a(Unknown Source:124)
	at androidx.compose.ui.platform.x.J(Unknown Source:80)
	at androidx.compose.ui.platform.x.k(Unknown Source:375)
	at androidx.compose.ui.platform.x.dispatchTouchEvent(Unknown Source:75)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:553)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1908)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4584)
	at pc.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:511)
	at android.view.View.dispatchPointerEvent(View.java:16139)
	at com.xiaomi.mirror.MiuiMirrorImpl.isHandled(MiuiMirrorImpl.java:152)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7796)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7562)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6937)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6994)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6960)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7125)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6968)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7182)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6941)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6994)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6960)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6968)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6941)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10088)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10039)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10003)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10237)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:307)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:275)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:10174)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:10336)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1634)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1643)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1176)
	at android.view.Choreographer.doFrame(Choreographer.java:1073)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1609)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8671)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: DP: [androidx.compose.ui.platform.g0@b14a399, cl@2f8765e, cF1{Cancelling}@28f3a3f, d9@6752f0c]
```

### 备注 / Addition details

在下载页面内，拉动右侧的快速阅览按钮闪退。概率100%。在更新到最新的版本后也是闪退

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.12

### EhViewer CI 版本 / EhViewer CI Version

5bb0333

### Android 系统版本 / Android version

澎湃os1.0.18.0

### 设备型号 / Device model

红米k70pro

### SoC 型号 / Soc model

骁龙8+3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by qq1724737202** [comment]
不是下载闪退，是下载页面里，拉动右侧的阅览块导致软件崩溃闪退。

**Comment by qq1724737202** [comment]
没人管了吗😂

**Comment by UjuiUjuMandan** [comment]
> 没人管了吗😂

README 里都写了只维护直连。
